# Generated by Django 3.1.3 on 2020-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
